### ISSUE TITLE
Dockerfile libcrypt package installation fails

### ISSUE THREAD

**Issue by mattsinfield** [aws-samples/aws-codepipeline-devsecops-amazoneks#3]
After following the install instructions the pipelines executes but the codebuild project Build-cicd-aws-codepipeline-devsecops-amazoneks fails when adding crypto libraries to the image:

Step 9/16 : RUN apk add libcrypto3=3.0.8-r0 libssl3=3.0.8-r0
--
4954 | ---> Running in d0f1ce4f4703
4955 | ERROR: unable to select packages:
4956 | libcrypto3-3.0.8-r3:
4957 | breaks: world[libcrypto3=3.0.8-r0]
4958 | satisfies: wget-1.21.4-r0[so:libcrypto.so.3]
4959 | apk-tools-2.12.10-r1[so:libcrypto.so.3]
4960 | libssl3-3.0.8-r3[so:libcrypto.so.3]
4961 | libssl3-3.0.8-r3:
4962 | breaks: world[libssl3=3.0.8-r0]
4963 | satisfies: wget-1.21.4-r0[so:libssl.so.3]
4964 | apk-tools-2.12.10-r1[so:libssl.so.3]
4965 | The command '/bin/sh -c apk add libcrypto3=3.0.8-r0 libssl3=3.0.8-r0' returned a non-zero code: 4

**Comment by vanvolkan** [comment]
I changed that line to:
RUN apk add libcrypto3=3.0.8-r3 libssl3=3.0.8-r3
which fixed the issue.

**Comment by maheshr-amzn** [comment]
@mattsinfield @vanvolkan Sorry for the delay and thanks for reaching out. It's a package version issue. i will fix it and publish   it.

**Comment by mattsinfield** [comment]
Great - thanks both.

**Comment by jaradtke-aws** [comment]
@maheshr-amzn - I'd like to close this if the updates have occurred and are successful.
